import React from 'react';

import { Card, CardHeader, CardBody
} from 'reactstrap'

import './SortingVisualizer.css';

import { random } from '../Utils';
import SortMenu from './SortMenu';
import { selectionSort, insertionSort, mergeSort, sortAlgorithms } from './SortAlgorithms';

// Size of array
const ARRAY_SIZE = 25;
// Minimum value in array
const MIN_VALUE = 5;
// Maximum value in array
const MAX_VALUE = 500;
// Speed between animations in miliseconds
const SPEED = 250;

// Unsorted bar color
const UNSORTED = "pink";

/**
 * Represents the sorting visualizer component.
 * 
 * @author Jake Waclawski
 */
class SortingVisualizer extends React.Component {
    constructor (props) {
        super(props);
        // Array of bar values
        this.state = { array: [] };
    }

    /**
     * Rebuilds the array with new random values.
     * 
     * @param {int} size size of array
     * @param {int} min minimum value
     * @param {int} max maximum value
     */
    rebuildArray (size, min, max) {
        const array = [];
        for (let i = 0; i < size; i++) { array.push(this.createBar(min, max)); }
        return array;
    }

    /**
     * Creates a new bar with a random value.
     * 
     * @param {*} min lower bound of value
     * @param {*} max upper bound of value
     * 
     * @returns the created bar
     */
    createBar (min, max) { return random(min, max); }

    /**
     * Rebuilds the array and regenerates the visual array bars.
     */
    reGenerateArray () { 
        var array = this.state.array;
        array = this.rebuildArray(ARRAY_SIZE, MIN_VALUE, MAX_VALUE);
        const bars = document.getElementsByClassName("bar");
        for (let i = 0; i < array.length; i++) { bars[i].style.backgroundColor = UNSORTED; }
        this.setState({array: array}); 
    }

    /**
     * Visualizes a given sorting algorithm.
     * 
     * @param {sortAlgorithms} algorithm sorting algorithm
     */
    visualizeSort (algorithm) {
        const array = this.state.array;
        var animations = [];

        switch (algorithm) {
            case sortAlgorithms.SELECTION:
                animations = selectionSort(array);
                break;
            case sortAlgorithms.INSERTION:
                animations = insertionSort(array);
                break;
            case sortAlgorithms.MERGE:
                animations = mergeSort(array);
                break;
            default:
                break;
        }

        this.animateSort(animations);
    }

    /**
     * Animates the process of the sorting algorithm. Iterates through an
     * array of animation steps generated by the algorithm.
     * 
     * @param {Array} animations 
     */
    animateSort (animations) {
        const bars = document.getElementsByClassName("bar");
        var i = 0
        for (const step of animations) {
            setTimeout(() => {
                for (const action of step) { 
                    if (action[0] === null) {
                        bars[action[1]].style.height = `${action[2]}px`;
                    } else {
                        for (let k = 1; k < action.length; k++) {
                            console.log(action);
                            bars[action[k]].style.backgroundColor = action[0]; 
                        }
                    }
                }
            }, SPEED * i++);
        }
    }

    /**
     * Runs on page load. Rebuilds the array.
     */
    componentDidMount () {
        const array = this.rebuildArray(ARRAY_SIZE, MIN_VALUE, MAX_VALUE);
        this.setState({array: array});
    }

    /**
     * Renders the sorting visualizer component.
     * 
     * @returns a <div> element representing the component
     */
    render () {
        console.log(this.state.array);

        return (
            <div>
                <Card>
                    <CardHeader>
                        <SortMenu sorter={this}/>
                    </CardHeader>
                    <CardBody>
                        <div className="bar-array">
                            {Array.from(this.state.array).map((bar, barIdx) => {
                                return (
                                    <div className="bar"
                                    key={barIdx}
                                    style={{
                                      backgroundColor: UNSORTED,
                                      height: `${bar}px`,
                                    }}/>
                                );
                            })}
                        </div>
                    </CardBody>
                </Card>
            </div>
        );
    }
}

export default SortingVisualizer;