import React from 'react';

import './SortingVisualizer.css';

import SortMenu from './Menu/SortMenu';
import { selectionSort, insertionSort, mergeSort, sortAlgorithms } from './Algorithms/SortAlgorithms';

// Size of array
const ARRAY_SIZE = 100;
// Minimum value in array
const MIN_VALUE = 5;
// Maximum value in array
const MAX_VALUE = 500;
// Default speed between animations in miliseconds
const DEFAULT_SPEED = 10;

// Unsorted bar color
const UNSORTED = "pink";

/**
 * Represents the sorting visualizer component.
 * 
 * @author Jake Waclawski
 */
class SortingVisualizer extends React.Component {
    constructor (props) {
        super(props);
        // Array of bar values
        this.state = { array: [] };
    }

    /**
     * Rebuilds the array with new random values.
     * 
     * @param {int} size size of array
     * @param {int} min minimum value
     * @param {int} max maximum value
     */
    rebuildArray (size, min, max) {
        const array = [];
        for (let i = 0; i < size; i++) { array.push(this.createBar(min, max)); }
        return array;
    }

    /**
     * Creates a new bar with a random value.
     * 
     * @param {int} min lower bound of value
     * @param {int} max upper bound of value
     * 
     * @returns the created bar
     */
    createBar (min, max) { return Math.floor(Math.random() * (max - min + 1) + min); }

    /**
     * Rebuilds the array and regenerates the visual array bars.
     * 
     * @param {int} size size of new array
     */
    reGenerateArray (size) { 
        if (!size) size = ARRAY_SIZE;

        const bars = document.getElementsByClassName("bar");
        for (let i = 0; i < this.state.array.length; i++) { bars[i].style.backgroundColor = UNSORTED; }

        const array = this.rebuildArray(size, MIN_VALUE, MAX_VALUE);
        this.setState({array: array}); 
    }

    /**
     * Visualizes a given sorting algorithm.
     * 
     * @param {sortAlgorithms} algorithm sorting algorithm
     * @param {int} speed time between animations in miliseconds
     */
    visualizeSort (algorithm, speed) {
        const array = this.state.array;
        var animations = [];

        switch (algorithm) {
            case sortAlgorithms.SELECTION:
                animations = selectionSort(array);
                break;
            case sortAlgorithms.INSERTION:
                animations = insertionSort(array);
                break;
            case sortAlgorithms.MERGE:
                animations = mergeSort(array);
                break;
            default:
                return;
        }

        this.animateSort(animations, speed);
    }

    /**
     * Animates the process of the sorting algorithm. Iterates through an
     * array of animation steps generated by the algorithm.
     * 
     * @param {Array} animations array of animations
     * @param {int} speed time between animations in miliseconds
     */
    animateSort (animations, speed) {
        if (!speed) speed = DEFAULT_SPEED;

        const bars = document.getElementsByClassName("bar");

        var i = 0
        for (const step of animations) {
            setTimeout(() => {
                for (const action of step) { 
                    if (action[0] === null) {
                        bars[action[1]].style.height = `${action[2]}px`;
                    } else {
                        for (let k = 1; k < action.length; k++) {
                            bars[action[k]].style.backgroundColor = action[0]; 
                        }
                    }
                }
            }, speed * i++);
        }
    }

    /**
     * Runs on page load. Rebuilds the array.
     */
    componentDidMount () {
        const array = this.rebuildArray(ARRAY_SIZE, MIN_VALUE, MAX_VALUE);
        this.setState({array: array});
    }

    /**
     * Renders the sorting visualizer component.
     * 
     * @returns a <div> element representing the component
     */
    render () {
        //console.log(this.state.array);

        return (
            <div className="sort-vis">
                <div className="sort-menu">
                    <SortMenu sorter={this}/>
                </div>
                <div className="array">
                    {Array.from(this.state.array).map((bar, barIdx) => {
                        return (
                            <div className="bar"
                            key={barIdx}
                            style={{
                                backgroundColor: UNSORTED,
                                height: `${bar}px`,
                            }}/>
                        );
                    })}
                </div>
            </div>
        );
    }
}

export default SortingVisualizer;